# NumPy

在深度学习的实现中，经常出现数组和矩阵的计算。NumPy的数组类（numpy.array）中提供了很多便捷的方法，在实现深度学习时，我们将使用这些方法

## 导入Numpy

In [4]:
import numpy as np

### 生成Numpy数组

要生成numpy数组需要使用np.array()方法，接收参数为列表。

In [5]:
x = np.array([1.0,2.0,3.0])
print(x)
type(x)

[1. 2. 3.]


numpy.ndarray

### 使用Numpy进行算数运算

In [6]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])
x+y

array([3., 6., 9.])

In [7]:
x-y

array([-1., -2., -3.])

In [8]:
x*y

array([ 2.,  8., 18.])

>这里需要注意的是，数组x和数组y的元素个数是相同的（两者均是元素个数为3 的一维数组）。当x和y的元素个数相同时，可以对各个元素进行算术运算。如果元素个数不同，程序就会报错，所以元素个数保持一致非常重要。


NumPy数组不仅可以进行element-wise 运算，也可以和单一的数值（标量）组合起来进行运算。此时，需要在NumPy数组的各个元素和标量之间进行运算。这个功能也被称为广播.

In [9]:
x/2.0

array([0.5, 1. , 1.5])

### 生成N维数组

In [20]:
A = np.array([[1,2],[3,5]])
print(A)

[[1 2]
 [3 5]]


In [19]:
A.shape # 获取数组的维数

(2, 2)

In [17]:
A.dtype # 获取数组中数据的类型

dtype('int32')

In [22]:
B = np.array([[3, 0],[0, 6]])

In [23]:
A+B

array([[ 4,  2],
       [ 3, 11]])

### 广播

In [ ]:
NumPy中，形状不同的数组之间也可以进行运算。之前的例中，在 2×2 的矩阵A和标量10之间进行了乘法运算。在这个过程中，标量10被扩展成了 2×2 的形状，然后再与矩阵A进行乘法运算。这个巧妙的功能称为广播（broadcast）。
1 1     10 10    10 10
2 3  *  10 10  = 20 30

In [28]:
A = np.array([[1,1],[2,3]])
B = np.array([10])
A*B

array([[10, 10],
       [20, 30]])

In [30]:
A = np.array([[1,1],[2,3]])
B = np.array([10,20])
A*B

array([[10, 20],
       [20, 60]])

In [ ]:
1 1     10 20    10 20
2 3  *  10 20  = 20 60

### 访问元素
访问元素的方法与嵌套列表相同。

In [31]:
X = np.array([[1,2],[3,4]])

In [33]:
X[0] # 第1行元素

array([1, 2])

In [34]:
X[0][0] # 第1行第1个元素

1

In [35]:
for row in X:
    print(row)

[1 2]
[3 4]


In [36]:
X.flatten() # 转换成一维数组

array([1, 2, 3, 4])

In [39]:
# 一次提取多个索引置的元素,组成一个新的np数组
X.flatten()[np.array([0,2,3])] 

array([1, 3, 4])

In [41]:
X>2 
# 多维数组可以直接与一个数进行比较，按位输出bool结果

array([[False, False],
       [ True,  True]])